// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Repository;

#nullable disable

namespace Repository.Databases.EFCore.Migrations.TestMigrations
{
    [DbContext(typeof(DevelopmentContext))]
    [Migration("20241031010212_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Repository.Banner", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Banners");
                });

            modelBuilder.Entity("Repository.BannerLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BannerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BannerId");

                    b.HasIndex("UserId");

                    b.ToTable("BannerLinks");
                });

            modelBuilder.Entity("Repository.Entities.Subscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Repository.Entities.Telegram", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Message")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NotifierId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Read")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RecipientId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NotifierId");

                    b.HasIndex("RecipientId");

                    b.ToTable("Telegrams");
                });

            modelBuilder.Entity("Repository.Feedback", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("Repository.Gathering", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Athleticisme")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Chaos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Competitiveness")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DegreeOfPrivacy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Extroversion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FriendlyLocation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupMaximum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupMinimum")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("HostId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Industriousness")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDynamic")
                        .HasColumnType("INTEGER");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("POINT")
                        .HasAnnotation("Sqlite:Srid", 4326);

                    b.Property<int>("NightOwl")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Openness")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Radius")
                        .HasColumnType("REAL");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HostId");

                    b.ToTable("Gatherings");
                });

            modelBuilder.Entity("Repository.GatheringLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("GatheringId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GatheringId");

                    b.HasIndex("UserId");

                    b.ToTable("GatheringLinks");
                });

            modelBuilder.Entity("Repository.GatheringReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("FilingDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("GatheringId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GatheringId");

                    b.HasIndex("UserId");

                    b.ToTable("GatheringReports");
                });

            modelBuilder.Entity("Repository.GuestClearance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Degree")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GatheringId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GatheringId");

                    b.HasIndex("UserId", "GatheringId")
                        .IsUnique();

                    b.ToTable("GuestClearances");
                });

            modelBuilder.Entity("Repository.Penalty", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("PenalizedId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PenalizedId");

                    b.ToTable("Penalties");
                });

            modelBuilder.Entity("Repository.Snapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("GatheringId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("PostedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GatheringId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Snapshots");
                });

            modelBuilder.Entity("Repository.SnapshotLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("SnapshotId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId");

                    b.HasIndex("UserId", "SnapshotId")
                        .IsUnique();

                    b.ToTable("SnapshotLinks");
                });

            modelBuilder.Entity("Repository.SnapshotReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("FilingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<long>("SnapshotId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId");

                    b.HasIndex("UserId");

                    b.ToTable("SnapshotReports");
                });

            modelBuilder.Entity("Repository.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessTries")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Athleticisme")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Chaos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Competitiveness")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CurrentGathering")
                        .HasColumnType("INTEGER");

                    b.Property<Point>("CurrentLocation")
                        .IsRequired()
                        .HasColumnType("POINT")
                        .HasAnnotation("Sqlite:Srid", 4326);

                    b.Property<double>("CurrentRadius")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Extroversion")
                        .HasColumnType("INTEGER");

                    b.Property<Point>("Haunt")
                        .IsRequired()
                        .HasColumnType("POINT")
                        .HasAnnotation("Sqlite:Srid", 4326);

                    b.Property<double>("HauntRadius")
                        .HasColumnType("REAL");

                    b.Property<int>("HauntWheight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Industriousness")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPhoneConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("JoinDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LockoutDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("NightOwl")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalisedEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Openness")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pseudonym")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Reputation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("TimeOfUserAgreement")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = -7L,
                            AccessTries = 3,
                            AccountStatus = 0,
                            Age = 25,
                            Athleticisme = 50,
                            Chaos = 50,
                            Competitiveness = 50,
                            CurrentLocation = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (7.544 53.483)"),
                            CurrentRadius = 10.0,
                            DateOfBirth = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "",
                            Extroversion = 50,
                            Haunt = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (7.54 53.483)"),
                            HauntRadius = 10.0,
                            HauntWheight = 0,
                            Industriousness = 50,
                            IsEmailConfirmed = false,
                            IsPhoneConfirmed = true,
                            JoinDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Apple Test Account",
                            NightOwl = 50,
                            NormalisedEmail = "",
                            NotificationId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Openness = 50,
                            PhoneNumber = "11002003007",
                            Pseudonym = "",
                            Reputation = 50,
                            SecurityStamp = "",
                            SoftDeleted = false,
                            TimeOfUserAgreement = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = -8L,
                            AccessTries = 3,
                            AccountStatus = 0,
                            Age = 25,
                            Athleticisme = 50,
                            Chaos = 50,
                            Competitiveness = 50,
                            CurrentLocation = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (7.544 53.483)"),
                            CurrentRadius = 10.0,
                            DateOfBirth = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "",
                            Extroversion = 50,
                            Haunt = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (7.54 53.483)"),
                            HauntRadius = 10.0,
                            HauntWheight = 0,
                            Industriousness = 50,
                            IsEmailConfirmed = false,
                            IsPhoneConfirmed = true,
                            JoinDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Google Test Account",
                            NightOwl = 50,
                            NormalisedEmail = "",
                            NotificationId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Openness = 50,
                            PhoneNumber = "11002003008",
                            Pseudonym = "",
                            Reputation = 50,
                            SecurityStamp = "",
                            SoftDeleted = false,
                            TimeOfUserAgreement = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Repository.UserRelationship", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("OtherId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SelfId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OtherId");

                    b.HasIndex("SelfId", "OtherId")
                        .IsUnique();

                    b.ToTable("UserRelationships");
                });

            modelBuilder.Entity("Repository.UserReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("FilingDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("GatheringId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<long>("OtherId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SelfId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GatheringId");

                    b.HasIndex("OtherId");

                    b.HasIndex("SelfId");

                    b.ToTable("UserReports");
                });

            modelBuilder.Entity("Repository.BannerLink", b =>
                {
                    b.HasOne("Repository.Banner", "Banner")
                        .WithMany("Links")
                        .HasForeignKey("BannerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.User", "User")
                        .WithMany("BannerLinks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Banner");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Entities.Subscription", b =>
                {
                    b.HasOne("Repository.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Entities.Telegram", b =>
                {
                    b.HasOne("Repository.User", "Notifier")
                        .WithMany("SentTelegrams")
                        .HasForeignKey("NotifierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.User", "Recipient")
                        .WithMany("ReceivedTelegrams")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Notifier");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("Repository.Feedback", b =>
                {
                    b.HasOne("Repository.User", "User")
                        .WithMany("Feedback")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Gathering", b =>
                {
                    b.HasOne("Repository.User", "Host")
                        .WithMany("HostedGatherings")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Host");
                });

            modelBuilder.Entity("Repository.GatheringLink", b =>
                {
                    b.HasOne("Repository.Gathering", "Gathering")
                        .WithMany("GatheringLink")
                        .HasForeignKey("GatheringId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.User", "User")
                        .WithMany("GatheringLinks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gathering");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.GatheringReport", b =>
                {
                    b.HasOne("Repository.Gathering", "Gathering")
                        .WithMany("GatheringReports")
                        .HasForeignKey("GatheringId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.User", "User")
                        .WithMany("GatheringReports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Gathering");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.GuestClearance", b =>
                {
                    b.HasOne("Repository.Gathering", "Gathering")
                        .WithMany("GuestClearances")
                        .HasForeignKey("GatheringId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.User", "User")
                        .WithMany("GuestClearances")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gathering");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Penalty", b =>
                {
                    b.HasOne("Repository.User", "Penalized")
                        .WithMany("Penalties")
                        .HasForeignKey("PenalizedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Penalized");
                });

            modelBuilder.Entity("Repository.Snapshot", b =>
                {
                    b.HasOne("Repository.Gathering", "Gathering")
                        .WithMany("Snapshots")
                        .HasForeignKey("GatheringId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.User", "Owner")
                        .WithMany("Snapshots")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gathering");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Repository.SnapshotLink", b =>
                {
                    b.HasOne("Repository.Snapshot", "Snapshot")
                        .WithMany("SnapshotLinks")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.User", "User")
                        .WithMany("SnapshotLinks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Snapshot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.SnapshotReport", b =>
                {
                    b.HasOne("Repository.Snapshot", "Snapshot")
                        .WithMany("Reports")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.User", "User")
                        .WithMany("SnapshotReports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Snapshot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.UserRelationship", b =>
                {
                    b.HasOne("Repository.User", "Other")
                        .WithMany("TargetUserRelationships")
                        .HasForeignKey("OtherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.User", "Self")
                        .WithMany("InitiatedUserRelationships")
                        .HasForeignKey("SelfId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Other");

                    b.Navigation("Self");
                });

            modelBuilder.Entity("Repository.UserReport", b =>
                {
                    b.HasOne("Repository.Gathering", "Gathering")
                        .WithMany("UserReports")
                        .HasForeignKey("GatheringId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Repository.User", "Other")
                        .WithMany("ReporteeList")
                        .HasForeignKey("OtherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.User", "Self")
                        .WithMany("ReporterList")
                        .HasForeignKey("SelfId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Gathering");

                    b.Navigation("Other");

                    b.Navigation("Self");
                });

            modelBuilder.Entity("Repository.Banner", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("Repository.Gathering", b =>
                {
                    b.Navigation("GatheringLink");

                    b.Navigation("GatheringReports");

                    b.Navigation("GuestClearances");

                    b.Navigation("Snapshots");

                    b.Navigation("UserReports");
                });

            modelBuilder.Entity("Repository.Snapshot", b =>
                {
                    b.Navigation("Reports");

                    b.Navigation("SnapshotLinks");
                });

            modelBuilder.Entity("Repository.User", b =>
                {
                    b.Navigation("BannerLinks");

                    b.Navigation("Feedback");

                    b.Navigation("GatheringLinks");

                    b.Navigation("GatheringReports");

                    b.Navigation("GuestClearances");

                    b.Navigation("HostedGatherings");

                    b.Navigation("InitiatedUserRelationships");

                    b.Navigation("Penalties");

                    b.Navigation("ReceivedTelegrams");

                    b.Navigation("ReporteeList");

                    b.Navigation("ReporterList");

                    b.Navigation("SentTelegrams");

                    b.Navigation("SnapshotLinks");

                    b.Navigation("SnapshotReports");

                    b.Navigation("Snapshots");

                    b.Navigation("Subscriptions");

                    b.Navigation("TargetUserRelationships");
                });
#pragma warning restore 612, 618
        }
    }
}
