// <auto-generated />
using System;
using CrazyLizard.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrazyLizard.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250917204252_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Repository.Entities.Block", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("BlockDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("BlockedId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BlockerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BlockedId");

                    b.HasIndex("BlockerId");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("Repository.Entities.Caption", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("PostId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Captions");
                });

            modelBuilder.Entity("Repository.Entities.Circle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CircleCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeaderPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("IssueSchedule")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("TimeOfCreation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CircleCode")
                        .IsUnique();

                    b.ToTable("Circles");
                });

            modelBuilder.Entity("Repository.Entities.Feedback", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comments")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("Repository.Entities.Issue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CircleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("DraftingEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DraftingStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeaderPath")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("IssueNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CircleId");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("Repository.Entities.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CirclesId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GatheringId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NotificationId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<long>("RecipientId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CirclesId");

                    b.HasIndex("RecipientId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Repository.Entities.Post", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("IssueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Layout")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("PostedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("IssueId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Repository.Entities.Recipient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(56)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("ManagerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProvinceOrState")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitNumber")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Recipients");
                });

            modelBuilder.Entity("Repository.Entities.Reports.Report", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Discriminator")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("FilingDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FilingUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Reports");

                    b.HasDiscriminator();

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Repository.Entities.Snapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long>("PostId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Snapshots");
                });

            modelBuilder.Entity("Repository.Entities.Subscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceToken")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Repository.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessTries")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long?>("CircleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CircleJoinDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPhoneConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IssuePosts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IssueReminders")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset>("JoinDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LockoutDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ProvidedPaymentDetails")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("TimeOfUserAgreement")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CircleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 2L,
                            AccessTries = 3,
                            AccountStatus = 0,
                            DateOfBirth = new DateOnly(1, 1, 1),
                            FirstName = "CANARY",
                            IsEmailConfirmed = false,
                            IsPhoneConfirmed = true,
                            IssuePosts = true,
                            IssueReminders = true,
                            JoinDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            NotificationId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PhoneNumber = "+15734922666",
                            ProvidedPaymentDetails = false,
                            SoftDeleted = false,
                            TimeOfUserAgreement = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 7L,
                            AccessTries = 3,
                            AccountStatus = 0,
                            DateOfBirth = new DateOnly(1, 1, 1),
                            FirstName = "Apple Test Account",
                            IsEmailConfirmed = false,
                            IsPhoneConfirmed = true,
                            IssuePosts = true,
                            IssueReminders = true,
                            JoinDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            NotificationId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PhoneNumber = "+11002003007",
                            ProvidedPaymentDetails = false,
                            SoftDeleted = false,
                            TimeOfUserAgreement = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 8L,
                            AccessTries = 3,
                            AccountStatus = 0,
                            DateOfBirth = new DateOnly(1, 1, 1),
                            FirstName = "Google Test Account",
                            IsEmailConfirmed = false,
                            IsPhoneConfirmed = true,
                            IssuePosts = true,
                            IssueReminders = true,
                            JoinDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            NotificationId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PhoneNumber = "+11002003008",
                            ProvidedPaymentDetails = false,
                            SoftDeleted = false,
                            TimeOfUserAgreement = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Repository.Entities.Word", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("Repository.Entities.Reports.PostReport", b =>
                {
                    b.HasBaseType("Repository.Entities.Reports.Report");

                    b.Property<long>("PostId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Type");

                    b.HasIndex("FilingUserId");

                    b.HasIndex("PostId");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Repository.Entities.Reports.UserReport", b =>
                {
                    b.HasBaseType("Repository.Entities.Reports.Report");

                    b.Property<long?>("GatheringId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReportedUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Type");

                    b.HasIndex("FilingUserId");

                    b.HasIndex("GatheringId");

                    b.HasIndex("ReportedUserId");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Repository.Entities.Block", b =>
                {
                    b.HasOne("Repository.Entities.User", "Blocked")
                        .WithMany("BlockedList")
                        .HasForeignKey("BlockedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Entities.User", "Blocker")
                        .WithMany("BlockerList")
                        .HasForeignKey("BlockerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Blocked");

                    b.Navigation("Blocker");
                });

            modelBuilder.Entity("Repository.Entities.Caption", b =>
                {
                    b.HasOne("Repository.Entities.Post", "Post")
                        .WithMany("Captions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Repository.Entities.Feedback", b =>
                {
                    b.HasOne("Repository.Entities.User", "User")
                        .WithMany("Feedback")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Entities.Issue", b =>
                {
                    b.HasOne("Repository.Entities.Circle", "Circle")
                        .WithMany("Issues")
                        .HasForeignKey("CircleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Circle");
                });

            modelBuilder.Entity("Repository.Entities.Notification", b =>
                {
                    b.HasOne("Repository.Entities.Circle", "Circles")
                        .WithMany("Notifications")
                        .HasForeignKey("CirclesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Repository.Entities.User", "Recipient")
                        .WithMany("Notifications")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Circles");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("Repository.Entities.Post", b =>
                {
                    b.HasOne("Repository.Entities.User", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Entities.Issue", "Issue")
                        .WithMany("Posts")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Repository.Entities.Recipient", b =>
                {
                    b.HasOne("Repository.Entities.User", "Manager")
                        .WithMany("Recipients")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Repository.Entities.Snapshot", b =>
                {
                    b.HasOne("Repository.Entities.Post", "Post")
                        .WithMany("Snapshots")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Repository.Entities.Subscription", b =>
                {
                    b.HasOne("Repository.Entities.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Entities.User", b =>
                {
                    b.HasOne("Repository.Entities.Circle", "Circle")
                        .WithMany("Members")
                        .HasForeignKey("CircleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Circle");
                });

            modelBuilder.Entity("Repository.Entities.Reports.PostReport", b =>
                {
                    b.HasOne("Repository.Entities.User", "FilingUser")
                        .WithMany("SnapshotReports")
                        .HasForeignKey("FilingUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Repository.Entities.Post", "Post")
                        .WithMany("Reports")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FilingUser");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Repository.Entities.Reports.UserReport", b =>
                {
                    b.HasOne("Repository.Entities.User", "FilingUser")
                        .WithMany("ReporterList")
                        .HasForeignKey("FilingUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Repository.Entities.Circle", "Gathering")
                        .WithMany()
                        .HasForeignKey("GatheringId");

                    b.HasOne("Repository.Entities.User", "ReportedUser")
                        .WithMany("ReportedList")
                        .HasForeignKey("ReportedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FilingUser");

                    b.Navigation("Gathering");

                    b.Navigation("ReportedUser");
                });

            modelBuilder.Entity("Repository.Entities.Circle", b =>
                {
                    b.Navigation("Issues");

                    b.Navigation("Members");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Repository.Entities.Issue", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Repository.Entities.Post", b =>
                {
                    b.Navigation("Captions");

                    b.Navigation("Reports");

                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("Repository.Entities.User", b =>
                {
                    b.Navigation("BlockedList");

                    b.Navigation("BlockerList");

                    b.Navigation("Feedback");

                    b.Navigation("Notifications");

                    b.Navigation("Posts");

                    b.Navigation("Recipients");

                    b.Navigation("ReportedList");

                    b.Navigation("ReporterList");

                    b.Navigation("SnapshotReports");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
