<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Migrations\TestDBMigrations\**" />
    <Compile Remove="TestDBMigrations\**" />
    <EmbeddedResource Remove="Migrations\TestDBMigrations\**" />
    <EmbeddedResource Remove="TestDBMigrations\**" />
    <None Remove="Migrations\TestDBMigrations\**" />
    <None Remove="TestDBMigrations\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.14.2" />
    <PackageReference Include="Azure.Security.KeyVault.Administration" Version="4.6.0" />
    <PackageReference Include="Azure.Security.KeyVault.Certificates" Version="4.8.0" />
    <PackageReference Include="Azure.Security.KeyVault.Keys" Version="4.8.0" />
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.8.0" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.25.0" />
    <PackageReference Include="EntityFrameworkCore.Exceptions.Sqlite" Version="8.1.3" />
    <PackageReference Include="EntityFrameworkCore.Exceptions.SqlServer" Version="8.1.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.NetTopologySuite" Version="9.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Serilog.Sinks.AzureApp" Version="3.1.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Migrations\ProductionMigrations\" />
    <Folder Include="Migrations\StagingMigrations\" />
    <Folder Include="Migrations\TestMigrations\" />
  </ItemGroup>

</Project>
