// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Repository;

#nullable disable

namespace Repository.Databases.EFCore.Migrations.ProductionMigrations
{
    [DbContext(typeof(AzureProductionContext))]
    partial class AzureProductionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Repository.Chat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Chats");

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Repository.ChatLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("HiddenFrom")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Muted")
                        .HasColumnType("bit");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatLinks");

                    b.HasData(
                        new
                        {
                            Id = -2L,
                            ConversationId = -2L,
                            LastSeen = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Muted = false,
                            SoftDeleted = false,
                            Type = 1,
                            UserId = -2L
                        });
                });

            modelBuilder.Entity("Repository.Connection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Connections");
                });

            modelBuilder.Entity("Repository.Entities.Subscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DeviceToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Repository.Entities.Telegram", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("NotifierId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Read")
                        .HasColumnType("bit");

                    b.Property<long>("RecipientId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("NotifierId");

                    b.HasIndex("RecipientId");

                    b.ToTable("Telegrams");
                });

            modelBuilder.Entity("Repository.Feedback", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("Repository.Gathering", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Athleticisme")
                        .HasColumnType("int");

                    b.Property<int>("Chaos")
                        .HasColumnType("int");

                    b.Property<int>("Competitiveness")
                        .HasColumnType("int");

                    b.Property<float>("Decay")
                        .HasColumnType("real");

                    b.Property<int>("DegreeOfPrivacy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Extroversion")
                        .HasColumnType("int");

                    b.Property<string>("FriendlyLocation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("GroupMaximum")
                        .HasColumnType("int");

                    b.Property<int>("GroupMinimum")
                        .HasColumnType("int");

                    b.Property<long?>("HostId")
                        .HasColumnType("bigint");

                    b.Property<int>("Industriousness")
                        .HasColumnType("int");

                    b.Property<bool>("IsDynamic")
                        .HasColumnType("bit");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography")
                        .HasAnnotation("Sqlite:Srid", 4326);

                    b.Property<int>("NightOwl")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("int");

                    b.Property<int>("Openness")
                        .HasColumnType("int");

                    b.Property<double>("Radius")
                        .HasColumnType("float");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TimeOfCreation")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Visibility")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HostId");

                    b.ToTable("Gatherings");
                });

            modelBuilder.Entity("Repository.GatheringLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("GatheringId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GatheringId");

                    b.HasIndex("UserId");

                    b.ToTable("GatheringLinks");
                });

            modelBuilder.Entity("Repository.GatheringReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("FilingDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("GatheringId")
                        .HasColumnType("bigint");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GatheringId");

                    b.HasIndex("UserId");

                    b.ToTable("GatheringReports");
                });

            modelBuilder.Entity("Repository.GuestClearance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Degree")
                        .HasColumnType("int");

                    b.Property<long>("GatheringId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GatheringId");

                    b.HasIndex("UserId");

                    b.ToTable("GuestClearances");
                });

            modelBuilder.Entity("Repository.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("UserId");

                    b.ToTable("Messages");

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Repository.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("GatheringId")
                        .HasColumnType("bigint");

                    b.Property<string>("NotificationId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<long>("RecipientId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GatheringId");

                    b.HasIndex("RecipientId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Repository.Penalty", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("PenalizedId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PenalizedId");

                    b.ToTable("Penalties");
                });

            modelBuilder.Entity("Repository.Snapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("GatheringId")
                        .HasColumnType("bigint");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("PostedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("GatheringId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Snapshots");
                });

            modelBuilder.Entity("Repository.SnapshotLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("SnapshotId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId");

                    b.HasIndex("UserId");

                    b.ToTable("SnapshotLinks");
                });

            modelBuilder.Entity("Repository.SnapshotReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("FilingDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long>("SnapshotId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId");

                    b.HasIndex("UserId");

                    b.ToTable("SnapshotReports");
                });

            modelBuilder.Entity("Repository.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessTries")
                        .HasColumnType("int");

                    b.Property<int>("AccountStatus")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Athleticisme")
                        .HasColumnType("int");

                    b.Property<int>("Chaos")
                        .HasColumnType("int");

                    b.Property<bool>("CompanionActivity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("CompanionshipCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Competitiveness")
                        .HasColumnType("int");

                    b.Property<long?>("CurrentGathering")
                        .HasColumnType("bigint");

                    b.Property<Point>("CurrentLocation")
                        .IsRequired()
                        .HasColumnType("geography")
                        .HasAnnotation("Sqlite:Srid", 4326);

                    b.Property<double>("CurrentRadius")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("DateOfBirth")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Extroversion")
                        .HasColumnType("int");

                    b.Property<bool>("GatheringActivity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("GatheringDiscovery")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("GatheringReminders")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Point>("Haunt")
                        .IsRequired()
                        .HasColumnType("geography")
                        .HasAnnotation("Sqlite:Srid", 4326);

                    b.Property<double>("HauntRadius")
                        .HasColumnType("float");

                    b.Property<int>("HauntWeight")
                        .HasColumnType("int");

                    b.Property<int>("Industriousness")
                        .HasColumnType("int");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPhoneConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("JoinDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LockoutDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NightOwl")
                        .HasColumnType("int");

                    b.Property<string>("NormalisedEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Openness")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Reputation")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("SocialInvitations")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("TimeOfUserAgreement")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = -2L,
                            AccessTries = 3,
                            AccountStatus = 0,
                            Age = 25,
                            Athleticisme = 50,
                            Chaos = 50,
                            CompanionActivity = true,
                            CompanionshipCode = "",
                            Competitiveness = 50,
                            CurrentLocation = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (7.544 53.483)"),
                            CurrentRadius = 10.0,
                            DateOfBirth = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "",
                            Extroversion = 50,
                            GatheringActivity = true,
                            GatheringDiscovery = true,
                            GatheringReminders = true,
                            Haunt = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (7.54 53.483)"),
                            HauntRadius = 10.0,
                            HauntWeight = 0,
                            Industriousness = 50,
                            IsEmailConfirmed = false,
                            IsPhoneConfirmed = true,
                            JoinDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "CANARY",
                            NightOwl = 50,
                            NormalisedEmail = "",
                            NotificationId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Openness = 50,
                            PhoneNumber = "15734922666",
                            Reputation = 50,
                            SecurityStamp = "",
                            SocialInvitations = true,
                            SoftDeleted = false,
                            TimeOfUserAgreement = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = -7L,
                            AccessTries = 3,
                            AccountStatus = 0,
                            Age = 25,
                            Athleticisme = 50,
                            Chaos = 50,
                            CompanionActivity = true,
                            CompanionshipCode = "",
                            Competitiveness = 50,
                            CurrentLocation = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (7.544 53.483)"),
                            CurrentRadius = 10.0,
                            DateOfBirth = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "",
                            Extroversion = 50,
                            GatheringActivity = true,
                            GatheringDiscovery = true,
                            GatheringReminders = true,
                            Haunt = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (7.54 53.483)"),
                            HauntRadius = 10.0,
                            HauntWeight = 0,
                            Industriousness = 50,
                            IsEmailConfirmed = false,
                            IsPhoneConfirmed = true,
                            JoinDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Apple Test Account",
                            NightOwl = 50,
                            NormalisedEmail = "",
                            NotificationId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Openness = 50,
                            PhoneNumber = "11002003007",
                            Reputation = 50,
                            SecurityStamp = "",
                            SocialInvitations = true,
                            SoftDeleted = false,
                            TimeOfUserAgreement = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = -8L,
                            AccessTries = 3,
                            AccountStatus = 0,
                            Age = 25,
                            Athleticisme = 50,
                            Chaos = 50,
                            CompanionActivity = true,
                            CompanionshipCode = "",
                            Competitiveness = 50,
                            CurrentLocation = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (7.544 53.483)"),
                            CurrentRadius = 10.0,
                            DateOfBirth = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "",
                            Extroversion = 50,
                            GatheringActivity = true,
                            GatheringDiscovery = true,
                            GatheringReminders = true,
                            Haunt = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (7.54 53.483)"),
                            HauntRadius = 10.0,
                            HauntWeight = 0,
                            Industriousness = 50,
                            IsEmailConfirmed = false,
                            IsPhoneConfirmed = true,
                            JoinDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Google Test Account",
                            NightOwl = 50,
                            NormalisedEmail = "",
                            NotificationId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Openness = 50,
                            PhoneNumber = "11002003008",
                            Reputation = 50,
                            SecurityStamp = "",
                            SocialInvitations = true,
                            SoftDeleted = false,
                            TimeOfUserAgreement = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Repository.UserRelationship", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("OtherId")
                        .HasColumnType("bigint");

                    b.Property<long>("SelfId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OtherId");

                    b.HasIndex("SelfId");

                    b.ToTable("UserRelationships");
                });

            modelBuilder.Entity("Repository.UserReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("FilingDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("GatheringId")
                        .HasColumnType("bigint");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long>("OtherId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SelfId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GatheringId");

                    b.HasIndex("OtherId");

                    b.HasIndex("SelfId");

                    b.ToTable("UserReports");
                });

            modelBuilder.Entity("Repository.Word", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("Repository.BroadcastChat", b =>
                {
                    b.HasBaseType("Repository.Chat");

                    b.Property<string>("Title")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Title");

                    b.HasDiscriminator().HasValue(3);

                    b.HasData(
                        new
                        {
                            Id = -2L,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SoftDeleted = false,
                            Type = 3,
                            Title = "CANARY Team"
                        });
                });

            modelBuilder.Entity("Repository.GatheringChat", b =>
                {
                    b.HasBaseType("Repository.Chat");

                    b.Property<long>("GatheringId")
                        .HasColumnType("bigint");

                    b.HasIndex("GatheringId")
                        .IsUnique()
                        .HasFilter("[GatheringId] IS NOT NULL");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Repository.GroupChat", b =>
                {
                    b.HasBaseType("Repository.Chat");

                    b.Property<string>("Title")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Title");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Repository.PrivateChat", b =>
                {
                    b.HasBaseType("Repository.Chat");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Repository.ActivityMessage", b =>
                {
                    b.HasBaseType("Repository.Message");

                    b.Property<int>("ActivityType")
                        .HasColumnType("int");

                    b.Property<long?>("ActorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TargetId")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("Text");

                    b.HasIndex("ActorId");

                    b.HasIndex("TargetId");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Repository.GatheringInviteMessage", b =>
                {
                    b.HasBaseType("Repository.Message");

                    b.Property<long>("GatheringId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("GatheringId");

                    b.HasIndex("GatheringId");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("Repository.GatheringShareMessage", b =>
                {
                    b.HasBaseType("Repository.Message");

                    b.Property<long>("GatheringId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("GatheringId");

                    b.HasIndex("GatheringId");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("Repository.ImageMessage", b =>
                {
                    b.HasBaseType("Repository.Message");

                    b.Property<Guid>("StorageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Repository.ProfileMessage", b =>
                {
                    b.HasBaseType("Repository.Message");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.HasIndex("ProfileId");

                    b.HasDiscriminator().HasValue(6);
                });

            modelBuilder.Entity("Repository.TextMessage", b =>
                {
                    b.HasBaseType("Repository.Message");

                    b.Property<string>("Text")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("Text");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Repository.ChatLink", b =>
                {
                    b.HasOne("Repository.Chat", "Chat")
                        .WithMany("ChatLinks")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Repository.User", "User")
                        .WithMany("ChatLinks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Connection", b =>
                {
                    b.HasOne("Repository.User", "User")
                        .WithMany("Connections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Entities.Subscription", b =>
                {
                    b.HasOne("Repository.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Entities.Telegram", b =>
                {
                    b.HasOne("Repository.User", "Notifier")
                        .WithMany("SentTelegrams")
                        .HasForeignKey("NotifierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.User", "Recipient")
                        .WithMany("ReceivedTelegrams")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Notifier");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("Repository.Feedback", b =>
                {
                    b.HasOne("Repository.User", "User")
                        .WithMany("Feedback")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Gathering", b =>
                {
                    b.HasOne("Repository.User", "Host")
                        .WithMany("HostedGatherings")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Host");
                });

            modelBuilder.Entity("Repository.GatheringLink", b =>
                {
                    b.HasOne("Repository.Gathering", "Gathering")
                        .WithMany("GatheringLink")
                        .HasForeignKey("GatheringId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.User", "User")
                        .WithMany("GatheringLinks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gathering");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.GatheringReport", b =>
                {
                    b.HasOne("Repository.Gathering", "Gathering")
                        .WithMany("GatheringReports")
                        .HasForeignKey("GatheringId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.User", "User")
                        .WithMany("GatheringReports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Gathering");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.GuestClearance", b =>
                {
                    b.HasOne("Repository.Gathering", "Gathering")
                        .WithMany("GuestClearances")
                        .HasForeignKey("GatheringId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.User", "User")
                        .WithMany("GuestClearances")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gathering");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Message", b =>
                {
                    b.HasOne("Repository.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Repository.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Notification", b =>
                {
                    b.HasOne("Repository.Gathering", "Gathering")
                        .WithMany("Notifications")
                        .HasForeignKey("GatheringId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.User", "Recipient")
                        .WithMany("Notifications")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gathering");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("Repository.Penalty", b =>
                {
                    b.HasOne("Repository.User", "Penalized")
                        .WithMany("Penalties")
                        .HasForeignKey("PenalizedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Penalized");
                });

            modelBuilder.Entity("Repository.Snapshot", b =>
                {
                    b.HasOne("Repository.Gathering", "Gathering")
                        .WithMany("Snapshots")
                        .HasForeignKey("GatheringId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.User", "Owner")
                        .WithMany("Snapshots")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gathering");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Repository.SnapshotLink", b =>
                {
                    b.HasOne("Repository.Snapshot", "Snapshot")
                        .WithMany("SnapshotLinks")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.User", "User")
                        .WithMany("SnapshotLinks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Snapshot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.SnapshotReport", b =>
                {
                    b.HasOne("Repository.Snapshot", "Snapshot")
                        .WithMany("Reports")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.User", "User")
                        .WithMany("SnapshotReports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Snapshot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.UserRelationship", b =>
                {
                    b.HasOne("Repository.User", "Other")
                        .WithMany("TargetUserRelationships")
                        .HasForeignKey("OtherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.User", "Self")
                        .WithMany("InitiatedUserRelationships")
                        .HasForeignKey("SelfId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Other");

                    b.Navigation("Self");
                });

            modelBuilder.Entity("Repository.UserReport", b =>
                {
                    b.HasOne("Repository.Gathering", "Gathering")
                        .WithMany("UserReports")
                        .HasForeignKey("GatheringId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Repository.User", "Other")
                        .WithMany("ReporteeList")
                        .HasForeignKey("OtherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.User", "Self")
                        .WithMany("ReporterList")
                        .HasForeignKey("SelfId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Gathering");

                    b.Navigation("Other");

                    b.Navigation("Self");
                });

            modelBuilder.Entity("Repository.GatheringChat", b =>
                {
                    b.HasOne("Repository.Gathering", "Gathering")
                        .WithOne("Chat")
                        .HasForeignKey("Repository.GatheringChat", "GatheringId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gathering");
                });

            modelBuilder.Entity("Repository.ActivityMessage", b =>
                {
                    b.HasOne("Repository.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId");

                    b.HasOne("Repository.User", "Target")
                        .WithMany()
                        .HasForeignKey("TargetId");

                    b.Navigation("Actor");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("Repository.GatheringInviteMessage", b =>
                {
                    b.HasOne("Repository.Gathering", "Gathering")
                        .WithMany("Invites")
                        .HasForeignKey("GatheringId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gathering");
                });

            modelBuilder.Entity("Repository.GatheringShareMessage", b =>
                {
                    b.HasOne("Repository.Gathering", "Gathering")
                        .WithMany("Shares")
                        .HasForeignKey("GatheringId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gathering");
                });

            modelBuilder.Entity("Repository.ProfileMessage", b =>
                {
                    b.HasOne("Repository.User", "Profile")
                        .WithMany("Shares")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Repository.Chat", b =>
                {
                    b.Navigation("ChatLinks");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Repository.Gathering", b =>
                {
                    b.Navigation("Chat");

                    b.Navigation("GatheringLink");

                    b.Navigation("GatheringReports");

                    b.Navigation("GuestClearances");

                    b.Navigation("Invites");

                    b.Navigation("Notifications");

                    b.Navigation("Shares");

                    b.Navigation("Snapshots");

                    b.Navigation("UserReports");
                });

            modelBuilder.Entity("Repository.Snapshot", b =>
                {
                    b.Navigation("Reports");

                    b.Navigation("SnapshotLinks");
                });

            modelBuilder.Entity("Repository.User", b =>
                {
                    b.Navigation("ChatLinks");

                    b.Navigation("Connections");

                    b.Navigation("Feedback");

                    b.Navigation("GatheringLinks");

                    b.Navigation("GatheringReports");

                    b.Navigation("GuestClearances");

                    b.Navigation("HostedGatherings");

                    b.Navigation("InitiatedUserRelationships");

                    b.Navigation("Messages");

                    b.Navigation("Notifications");

                    b.Navigation("Penalties");

                    b.Navigation("ReceivedTelegrams");

                    b.Navigation("ReporteeList");

                    b.Navigation("ReporterList");

                    b.Navigation("SentTelegrams");

                    b.Navigation("Shares");

                    b.Navigation("SnapshotLinks");

                    b.Navigation("SnapshotReports");

                    b.Navigation("Snapshots");

                    b.Navigation("Subscriptions");

                    b.Navigation("TargetUserRelationships");
                });
#pragma warning restore 612, 618
        }
    }
}
